
version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
    rebase-strategy: "disabled"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
