gpt_answer_service_url = "grpc://0.0.0.0:50051"
service_name = "rust-api-server-local"

[server]
port = 8888

[log]
level = "info"

[db.pg]
max_size = 100
url = "postgres://postgres:changeme@localhost:5432/postgres"
