service_name = "rust-api-server-local"
gpt_answer_service_url = "grpc://0.0.0.0:50051"

[server]
port = 8888

[log]
level = "info"

[db.pg]
url = "postgres://postgres:changeme@localhost:5432/postgres"
max_size = 100