[package]
name = "library"
version = "0.1.0"
edition = "2021"

[lib]
doctest = true

[dependencies]
warp = "0.3"
tokio = { version = "1.2", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
config = "0.14.0"
readonly = "0.2.12"
deadpool-diesel = { version = "0.5.0", features = ["postgres", "serde"] }
clap = { version = "4.4.7", features = ["derive"] }
tracing = { version = "0.1", features = ["tracing-attributes"] }
async-trait = "0.1.77"
diesel = { version = "2.1.0", features = ["postgres", "postgres_backend", "uuid"] }
uuid = { version = "1.7.0", features = ["serde", "v4", "fast-rng", "macro-diagnostics"] }
serde_json = "1.0"
testcontainers = "0.15.0"
testcontainers-modules = {version = "0.3.5", features = ["postgres"]}
rand = "0.8.4"
diesel_migrations = "2.1.0"