service_name = "rust-api-server"
exporter_endpoint = "http://localhost:7281"

[server]
url = "0.0.0.0"
port = 8000

[pg]
user = 'postgres'
password = 'postgres'
host = '127.0.0.1'
port = 5432
dbname = 'rust_template_db'
pool.max_size = 16
