bin = []
bench = []
test = []
example = []

[package]
name = "common"
edition = "2021"
version = "0.0.1"
autobins = true
autoexamples = true
autotests = true
autobenches = true

[dependencies]
config = "0.14.0"
glob = "0.3.1"
tracing = "0.1"
tracing-bunyan-formatter = "0.3.9"
tracing-opentelemetry = "0.23.0"

[dependencies.opentelemetry]
version = "0.22.0"

[dependencies.opentelemetry-otlp]
version = "0.15.0"
features = ["tonic"]

[dependencies.opentelemetry-semantic-conventions]
version = "0.14.0"

[dependencies.opentelemetry_sdk]
version = "0.22.1"
features = ["rt-tokio"]

[dependencies.serde]
version = "1.0"
features = ["derive"]

[dependencies.tracing-subscriber]
version = "0.3.18"
features = ["env-filter"]

[lib]
path = "src/lib.rs"
name = "common"
test = true
doctest = true
bench = true
doc = true
plugin = false
proc-macro = false
harness = true
edition = "2021"
required-features = []
crate-type = ["rlib"]
